#!/usr/bin/perl -w -I/opt/eprints2/perl_lib

use EPrints::Session;

use strict;

EPrints::Session::start()

my $url = "http://www.google.com/search?q=".&SESSION->param( "q" );
$url .= "+site:".&ARCHIVE->get_conf( "host" );

&SESSION->redirect( $url );
exit;
