eprints-current.tar.gz:
	./makepackage.sh HEAD "Build: `date`" licenses/license-1.0.txt eprints-current.tar.gz


eprints-1.0.tar.gz:
	./makepackage.sh eprints-1.0 "Version 1.0 (29/11/2000)" licenses/license-1.0.txt eprints-1.0.tar.gz


eprints-beta-2.tar.gz:
	./makepackage.sh eprints-beta-2 "Beta-2 (19/9/2000)" licenses/license-beta-2.txt eprints-beta-2.tar.gz


eprints-beta-1.tar.gz:
	./makepackage.sh eprints-beta-1 "Beta-1 (4/7/2000)" license-beta-1.txt eprints-beta-1.tar.gz
	
