eprints-current.tar.gz:
	./makepackage.sh HEAD "Build: `date`" licenses/license-1.2pre.txt eprints-current

eprints-1.1.2.tar.gz:
	./makepackage.sh eprints-1_1_2 "Version 1.1.2 (20/02/2001)" licenses/license-1.1.txt eprints-1.1.2

eprints-1.1.1.tar.gz:
	./makepackage.sh eprints-1_1_1 "Version 1.1.1 (23/01/2001)" licenses/license-1.1.txt eprints-1.1.1

eprints-1.1.tar.gz:
	./makepackage.sh eprints-1_1 "Version 1.1 (23/01/2001)" licenses/license-1.1.txt eprints-1.1



eprints-1.0.tar.gz:
	./makepackage.sh eprints-1_0 "Version 1.0 (29/11/2000)" licenses/license-1.0.txt eprints-1.0


eprints-beta-2.tar.gz:
	./makepackage.sh eprints-beta-2 "Beta-2 (19/9/2000)" licenses/license-beta-2.txt eprints-beta-2


eprints-beta-1.tar.gz:
	./makepackage.sh eprints-beta-1 "Beta-1 (4/7/2000)" license-beta-1.txt eprints-beta-1
	
