#!/usr/bin/perl -w -I/opt/eprints2/perl_lib

use EPrints::Session;
use strict;

my $noise = 1;

# Set STDOUT to auto flush (without needing a \n)
$|=1;

my $session = new EPrints::Session( 1, $ARGV[0], $noise, 1 );
exit( 1 ) unless defined $session;

# TODO: warn if unsupported property encountered?
# TODO: NOT NULL userid_actual

if( !$session->get_db->has_table( "rae_moe" ) )
{
	my $sql = "CREATE TABLE rae_moe (userid INT(11) PRIMARY KEY, userid_actual INT(11)";
	foreach my $field ( @{ $session->get_archive->get_conf( "rae", "fields", "moe" ) } )
	{
		my $metafield = EPrints::MetaField->new( 
			archive => $session->get_archive(),
			confid => "rae",
			%$field,
		);
		$sql .= ", " . $metafield->get_sql_type;
	}
	$sql .= ")";
	if( !$session->get_db->do( $sql ) )
	{
		my $error = $session->get_db()->error();
		print STDERR "DB Error: $error\n";
	}
}

if( !$session->get_db->has_table( "rae_selections" ) )
{
	my $sql = "CREATE TABLE rae_selections (userid INT(11), eprintid INT(11), userid_actual INT(11), PRIMARY KEY (userid, eprintid)";
	foreach my $field ( @{ $session->get_archive->get_conf( "rae", "fields", "edit" ) } )
	{
		my $metafield = EPrints::MetaField->new( 
			archive => $session->get_archive(),
			confid => "rae",
			%$field,
		);
		$sql .= ", " . $metafield->get_sql_type;
	}
	$sql .= ")";
	if( !$session->get_db->do( $sql ) )
	{
		my $error = $session->get_db()->error();
		print STDERR "DB Error: $error\n";
	}
}

$session->terminate();
exit;


