#!/usr/bin/perl -w

use CGI;

$p = new CGI();

my $latex = $p->param( "latex" );
$latex =~ s/_([0-9A-F][0-9A-F])/chr(hex($&))/eig;

print "Content-type: image/png\n\n";
$ofile = $latex;
$ofile =~ s/[^a-z0-9]/sprintf('-%02X',ord($&))/ieg;

$TMPDIR = "/home/cjg/mathmode";
chdir( $TMPDIR );

my $ofile = $latex;
$ofile =~ s/[^a-z0-9]/sprintf('_%02X',ord($&))/ieg;
$ofile.=".png";
if( -e $ofile ) 
{
	print `cat -- $ofile`;
	exit;
}

open( TEX, ">$$.tex" );
print TEX <<END;
\\scrollmode
\\documentclass{slides}
\\begin{document}
$latex
\\end{document}
END
close TEX;
`latex $$.tex`;
`dvips $$.dvi -o $$.ps`;
`convert $$.ps -crop 0x0+2+2 '$ofile'`;
print `cat -- $ofile`;
`rm $$.*`;
