#!/bin/sh

while [ "x$PASSWORD1" = "x" -o "x$PASSWORD1" != "x$PASSWORD2" ]; do

	echo 1>&2 -n $1
	stty -echo
	read PASSWORD1
	stty echo
	echo 1>&2 ""
	echo 1>&2 -n "Retype to confirm: "
	stty -echo
	read PASSWORD2
	stty echo
	echo 1>&2 ""

	if test "x$PASSWORD1" = "x" ; then
		echo 1>&2 "Can't use empty password"
	else
		if test "x$PASSWORD1" = "x$PASSWORD2" ; then
			echo $PASSWORD1
			exit 0
		else
			echo 1>&2 "Passwords don't match"
		fi
	fi
done
