=head1 Trouble Shooting 

This section covers some things which can go wrong and why. If you have a suggestion for this section, let us know!

It will grow as people suggest new problems and solutions. Check the http://www.eprints.org/ website for the latest version.

=head1 Installation of EPrints and Required Software

=head2 Apache Crashes with a segmentation fault

Possible cause: apache linked against "expat" library. If you did not install apache from source then it is possible it was linked against the "expat" library. The problem arrises that it is also linked against mod_perl and when we use the XML::Parser module, that is also linked against expat. 2 expat's in one apache make it seg-fault. 

=head2 (Under SuSE Linux) Apache has problems compiling the mod rewrite module

With an error something like:

 In file included from mod_rewrite.c:93:
 mod_rewrite.h:133: ndbm.h: No such file or directory

Possible cause: Missing the ndbm library which is required (for some reason).

Solution: It comes as part of gdbm which is free. If working from a package you need gdbm-devel to get the header files (.h files).

=head1 Setting Up and Configuring a New Archive

=head2 System gives a "500 Internal Error" when viewing advanced search or submitting a document

Possible cause: No Subjects, Bug in code.

Solution: Run B<generate_subjects>

If this fails: Look at your apache error log for clues. If reporting a bug, include the errors
from the apache error log (often, but now always, found at C</usr/local/apache/logs/error_log>)

=head1 General

Solution: Build apache following the detailed instructions in the "requried software" section of the documentation.

=head2 Changes to the configuration didn't appear on the website

Possible cause: Several.

Solution: Rebuild everything by re-running (for the archive in question) B<generate_static>, B<generate_views>, B<generate_apacheconf> then stop and start apache. B<generate_abstracts> can take a long time, so don't run it unless you want to update the abstracts themselves.

=head2 Browse View page gives a "404 not found" error or fails to update.

Possible Cause: You didn't run the script which makes them!

Solution: Run generate_views, and ideally set it up to run automatically: see "Browse Views" in the installation section.

=head2 Apache takes a really long time to start (over a minute) and so do the command line scripts.

Possible Cause: EPrints loads several XML files at start up, and for some reason this requires a DNS
lookup if DNS lookup is unavailable then it has to timeout.

Solution: Make sure that the machine can perform DNS look-ups.
