
=head1 What is EPrints 2?

EPrints is generic archive software under development by the University of Southampton. It is intended to create a highly configurable web-based archive.

EPrints is primarily aimed at research papers, and the default configuration reflects this, but it could be easily used for other things such as images, research data, audio archives - anything that can be stored digitally.

=head1 Should I be installing EPrints 2 Alpha?

The current version of the software is alpha, which is to say it has bits missing and some bugs but does actually work.

You will almost certainly take some time to try out different configurations and get used to the software, so we would
suggest getting the configuration right with this version then installing the latest version when you want to make the
"proper" version.

=head1 What will it run on?

The system is being developed under RedHat Linux 7.1, it has been designed to work with any UNIX system, although at this stage of development we have no tested it on other systems yet. Feel free to report problems. The priority for getting it working is RedHat Linux, Other Linux, Solaris, Other UNIX. It will never run under Windows, the design is too closely entwined with the UNIX filesystem.


