######################################################################
#
# These are your system settings (as autogenerated by the installer).
# We suggest that you do not alter these, as future installers will
# probably override them.
# 
######################################################################
#
# This file is part of EPrints 2.
#
# EPrints 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# EPrints 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EPrints 2; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
######################################################################

# This file should only be use'd by EPrints::Config
package EPrints::SystemSettings;

$EPrints::SystemSettings::conf = {
                                   'apache' => '2',
                                   'virtualhost' => '',
                                   'enable_gdome' => 1,
                                   'version' => 'EPrints 2.3.13.1 (Sticky Toffee) [Born on 2005-09-20]',
                                   'disable_df' => 0,
                                   'archive_formats' => [
                                                          'zip',
                                                          'targz'
                                                        ],
                                   'archive_extensions' => {
                                                             'zip' => '.zip',
                                                             'targz' => '.tar.gz'
                                                           },
                                   'version_id' => '2.3.13.1',
                                   'base_path' => '/opt/eprints2',
                                   'show_ids_in_log' => 0,
                                   'group' => 'eprints',
                                   'version_history' => [
                                                          '2.3.13.1'
                                                        ],
                                   'smtp_server' => '',
                                   'user' => 'eprints',
                                   'invocation' => {
                                                     'convert_crop_white' => '$(convert) -crop 0x0 -bordercolor white -border 4x4 \'$(SOURCE)\' \'$(TARGET)\'',
                                                     'dvips' => '$(dvips) \'$(SOURCE)\' -o \'$(TARGET)\'',
                                                     'zip' => '$(unzip) 1>/dev/null 2>&1 -qq -o -d $(DIR) $(ARC)',
                                                     'sendmail' => '$(sendmail) -oi -t -odb --',
                                                     'wget' => '$(wget)  -r -L -q -m -nH -np --execute="robots=off" --cut-dirs=$(CUTDIRS) $(URL)',
                                                     'latex' => '$(latex) \'$(SOURCE)\'',
                                                     'targz' => '$(gunzip) -c < $(ARC) 2>/dev/null | $(tar) xf - -C $(DIR) >/dev/null 2>&1'
                                                   },
                                   'executables' => {
                                                      'convert' => '/usr/bin/convert',
                                                      'tar' => '/bin/tar',
                                                      'dvips' => '/usr/bin/dvips',
                                                      'gunzip' => '/bin/gunzip',
                                                      'sendmail' => '/usr/sbin/sendmail',
                                                      'unzip' => '/usr/bin/unzip',
                                                      'latex' => '/usr/bin/latex',
                                                      'wget' => '/usr/bin/wget'
                                                    }
                                 };

1;