#!/usr/bin/perl
@subs = 
qw/phys-astr phys-astrp phys-chms phys-erth phys-mtrl phys-mthm phys-phys phys-stts scls-accn scls-anth scls-arch scls-bhvr scls-bsns scls-cgnt scls-cmmn scls-crmn scls-ecnm scls-edct scls-ggrp scls-glgy scls-gphy scls-gvrn scls-intr scls-lw scls-mngm scls-pltc scls-psyc scls-sclw scls-sclg scls-urbn /;

for $id (1..1000) {
	$year = int rand(100)+1910;
	print "INSERT INTO archive (eprintid,username,type,title,year,ispublished,refereed,pubdom,abstract,conference,dir) VALUES ('$id','cjg','confpaper','title goes here',$year,0,0,0,'barble this be da abstract','conference name','/somedir');\n";
	for(1..rand(10)) {
		$sur = ("Harris","Porrige","Jones","Smith","Buffet","Summers")[int rand 6];
		$fir = ("Bill","Ben","Tim","Al","Will","Jules","Jon","Fred","Tony","Chris","Naomi","Jim")[int rand 12];
		$name = "$sur,$fir";
		print "INSERT INTO archiveauxauthors VALUES ('$id',$_,'$name');\n";
	}
	for(1..rand(4)) {
		$sub = $subs[int rand scalar @subs];
		print "INSERT INTO archiveauxsubjects VALUES ('$id',$_,'$sub');\n";
	}
	print STDERR "$id\n";
}
