#!/usr/bin/perl

use strict;

print "Content-type: text/html\n\n";
print '<body bgcolor="#ffffff">';


my $var=' xxx \pi xx$99*94$x {\em hello} -- $x= \frac{a\$-b+-\sqrt{b^{2}-4ac}}{2a}$ bye \pi';

#$var='A new study into the $E=MC^{2}$ equations and its $order^{2}$ implications.';



my $i=0;
my $mode = 0;
my $inslash = 0;
my $html = '';
my $buffer = '';
my $inmath = 0;
my $str = "";
my $inlatex = 0;
my $oldinlatex = 0;
$var.=' '; # easy way to force end of (simple) latex mode.
while($i<length($var))
{
	my $c= substr($var,$i,1);
	if( $inslash == 2 )
	{
		if( $c!~m/^[a-z]$/i)
		{
			$inslash = 0;
		}
	}
	if( $inslash == 0 )
	{
		if( $c eq "\\" )
		{
			$inslash = 1;
		}
		if( $c eq "{" )
		{
			++$mode;
		}
		if( ($inmath==0) && ($c eq '$') )
		{
			$inmath = 1;
		}
	} 
	elsif( $inslash == 1 )
	{
		if( $c=~m/^[a-z]$/i)
		{
			$inslash = 2;
		}
		else
		{
			$inslash = 3;
		}
	}
	
	$oldinlatex = $inlatex;	
	$inlatex = ( $mode>0 || $inslash>0 || $inmath>0 );

	if( !$inlatex && $oldinlatex )
	{
		my $param = $buffer;
		$param =~ s/[^a-z0-9]/sprintf('_%02X',ord($&))/ieg;
		$param =~ s/^\$(.*)\$$/$1/;
		$buffer=~s/"/&quot;/g;
		$html.='<img align="absbottom" src="eq2png?latex='.$param.'" alt="'.$buffer.'" border="0" />';
		$buffer = '';	
	}
	if ($inlatex)
	{
		$buffer.=$c;
	}
	else
	{
		$html.=$c;
	}
	
	if( $inslash == 0 )
	{
		if( $inmath==2 && ($c eq '$') )
		{
			$inmath = 0;
		}
		if( $inmath==1 )
		{
			$inmath = 2;
		}
		if( $c eq "}" )
		{
			--$mode;
		}
	}
	if( $inslash == 3 )
	{
		$inslash = 0;
	}
	++$i;
}
if( $mode )
{
	$html.=" [brace not closed]";
}
if( $inmath )
{
	$html.=" [math mode missing closing \$]";
}
print $html."\n";
