# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         TeX-Encode
version:      0.10
version_from: lib/TeX/Encode.pm
installdirs:  site
requires:
    Encode::Encoding:              0.1
    HTML::Entities:                1.27
    HTML::Parser:                  3.35
    Pod::LaTeX:                    0.56
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
