#!/usr/bin/perl

`(echo yes; echo "") | /opt/eprints/bin/erase_archive`;
`/opt/eprints/bin/create_databases`;

@subs = ();
print "SUBJECTS:\n";
my $basedir = "/opt/eprints/html/documents/demo";
`rm -rf $basedir`;
`mkdir $basedir`;
open(SUB,"/opt/eprints/cfg/subjects");
while(<SUB>) {
	chomp;
	@data = split(":");
	next unless $data[3];
	push @subs,$data[0] ;
	print "* $data[0]\n";
}
close SUB;
print "----\n";

open(MYSQL,"|mysql -B -u root eprints");
for $id (1..10000) {
	`mkdir $basedir/$id`;
	$year = int rand(100)+1910;
	print MYSQL "INSERT INTO archive (eprintid,username,type,title,year,ispublished,refereed,pubdom,abstract,conference,dir) VALUES ('$id','cjg','confpaper','title goes here',$year,0,0,0,'barble this be da abstract','conference name','demo/$id');\n";
	for(0..rand(5)+1) {
		$sur = ("Harris","Porrige","Jones","Smith","Buffet","Summers")[int rand 6];
		$fir = ("Bill","Ben","Tim","Al","Will","Jules","Jon","Fred","Tony","Chris","Naomi","Jim")[int rand 12];
		print MYSQL "INSERT INTO archiveauxauthors VALUES ('$id',$_,'$fir','$sur');\n";
	}
	for(0..rand(1)+1) {
		$sur = ("Harris","Porrige","Jones","Smith","Buffet","Summers")[int rand 6];
		$fir = ("Bill","Ben","Tim","Al","Will","Jules","Jon","Fred","Tony","Chris","Naomi","Jim")[int rand 12];
		print MYSQL "INSERT INTO archiveauxeditors VALUES ('$id',$_,'$fir','$sur');\n";
	}
	for(0..rand(3)+1) {
		$sub = $subs[int rand scalar @subs];
		print MYSQL "INSERT INTO archiveauxsubjects VALUES ('$id',$_,'$sub');\n";
	}
	print STDERR "$id\n";
}
close MYSQL;
