#!/usr/bin/perl

my $basedir = "/opt/eprints/html/documents/demo";
`rm -rf $basedir`;
`(echo yes; echo "") | /opt/eprints/bin/erase_archive`;
`/opt/eprints/bin/create_databases`;
my @firnames;
my $surnames;
open(ECSINFO,"ypcat ecsinfo|");
while(<ECSINFO>) {
	my @row = split /:/;
	foreach(@row){ s/[\\']/\\$&/g; }
	push @firnames,$row[2];
	push @firnames,$row[1];
	push @surnames,$row[0];
}
close ECSINFO;

@subs = ();
print "SUBJECTS:\n";
`mkdir $basedir`;
open(SUB,"/opt/eprints/cfg/subjects");
while(<SUB>) {
	chomp;
	@data = split(":");
	next unless $data[3];
	push @subs,$data[0] ;
	print "* $data[0]\n";
}
close SUB;
print "----\n";

open(MYSQL,"|mysql -B -u root eprints");
for $id (1..5000) {
	my $eprintid = "demo$id";
	`mkdir $basedir/$id`;
	$year = int rand(100)+1910;
	my ($c,$s) = ("","");
	if ($id % 8 == 0) 
	{
		$s = $id / 8;
	}
	if ($id % 1000 == 0)
	{
		$c = $id / 1000;
	}
	print MYSQL "INSERT INTO archive (eprintid,username,type,title,year,ispublished,refereed,pubdom,abstract,conference,dir,succeeds,commentary) VALUES ('$eprintid','cjg','confpaper','title goes here (#$id)',$year,0,0,0,'barble this be da abstract','conference name','demo/$id','$s','$c');\n";
	for(0..rand(5)+1) {
		$sur = $surnames[int rand scalar @surnames];
		$fir = $surnames[int rand scalar @firnames];
		print MYSQL "INSERT INTO archiveauxauthors VALUES ('$eprintid',$_,'$fir','$sur');\n";
	}
	for(0..rand(2)) {
		$sur = $surnames[int rand scalar @surnames];
		$fir = $surnames[int rand scalar @firnames];
		print MYSQL "INSERT INTO archiveauxeditors VALUES ('$eprintid',$_,'$fir','$sur');\n";
	}
	for(0..rand(3)+1) {
		$sub = $subs[int rand scalar @subs];
		print MYSQL "INSERT INTO archiveauxsubjects VALUES ('$eprintid',$_,'$sub');\n";
	}
	print STDERR "$eprintid\n";
}
close MYSQL;
