Word 2010 DepositMO plugin - API reference and source guide: uk.ac.soton.ses.SwordClientHandler Class Reference
uk.ac.soton.ses.SwordClientHandler Class Reference
SWORD 2 client implementation for .NET.
Public Member Functions
SwordClientHandler (string username, string password, string endpoint)
Creates a new SWORD 2 handler instance.
SwordClientHandler (string username, string password, string endpoint, bool resolveInbox)
Creates a new SWORD 2 handler instance.
string PostDocxToContainer (string docxFilename)
Deposits the .docx from the supplied filename to the initialised endpoint with the default content type.
string PostDocxToContainer (string docxFilename, string contentType)
Deposits the .docx from the supplied filename to the initialised endpoint with the supplied content type.
string DepositDocxToContents (string docxFilename, string contentType, string contentUri)
Deposits the .docx from the supplied filename to the supplied endpoint with the supplied content type.
string PostDocxToRepository (string docxFilename, string contentType, string endpoint)
Creates a container on the repository and posts the supplied docx file to that container.
string PostDocxToRepository (string docxFilename)
Creates a container on the repository and posts the supplied docx file to that container, using the default docx content type and the initialised endpoint on the instance.
string PostDocxToContainer (string docxFilename, string contentType, string containerUri)
Posts the supplied docx file to the supplied container.
string CreateContainer ()
Creates an empty container on the initialised repository.
string CreateContainer (string endpoint)
Creates an empty container on the repository at the supplied endpoint.
string GetResponseLocation (HttpWebRequest wr)
Gets the location of the response from the provided
HttpWebRequest
XmlDocument GetEprintInfo (string uri)
Gets information about the ePrint at the provided URI.
bool PutToDocument (string documentFileName, string endpoint)
Performs a PUT to the supplied endpoint with the supplied document filename using
DOCX_CONTENTTYPE
.
bool PutToDocument (string documentFileName, string endpoint, string contentType)
Performs a PUT to the supplied endpoint with the supplied document filename using the supplied content type.
XmlDocument DepositZipToEprint (string zipFileName)
Deposits the zip file in the supplied filename to the initialised endpoint with a gzip content type (to be formally standardised at the server side).
XmlDocument DepositZipToEprint (string zipFileName, string contentType)
Deposits the zip file in the supplied filename to the initalised endpoint with the supplied content type.
XmlDocument DepositEprintsXml (XmlDocument xmlDocument)
Deposits the EP2 XML document to the initialised endpoint with X-Packaging type
EP2_PACKAGING
XmlDocument DepositEprintsXml (string xmlFileName)
Deposits the EP2 XML document in the supplied filename to the initialised endpoint with X-Packaging type
EP2_PACKAGING
XmlDocument DepositXml (string xmlFileName, string xPackaging)
Deposits the XML document in the supplied filename to the initialised endpoint with the supplied X-Packaging type.
XmlDocument DepositXml (XmlDocument xmlDocument, string xPackaging)
Deposits the XML document to the initialised endpoint with the supplied X-Packaging type.
XmlDocument Delete (string swordUrl)
Deletes the document at the target address
swordUrl
.
XmlDocument ListRecords (bool stripEndpoint)
List all records at the endpoint.
XmlDocument ListRecords ()
List all records at the endpoint, by calling endpoint/id/records (
LIST_RECORD_PATH
).
Properties
string Username [set]
Sets the username associated with the repository.
string Password [set]
Sets the password associated with the repository.
string Endpoint [set]
Sets the endpoint associated with the repository.
Private Member Functions
internal void ResolveInbox ()
Resolves the inbox based on the currently-supplied endpoint.
HttpWebRequest GetBasicAuthAtomWebRequest (string targetUri)
Creates a web request instance to the target URI, adding in basic authorisation from the username and password on the instance, and setting the
accept
header of the request to be
application/atom+xml
HttpWebRequest GetBasicAuthAtomWebRequest (Uri targetUri)
Creates a web request instance to the target URI, adding in basic authorisation from the username and password on the instance, and setting the
accept
header of the request to be
application/atom+xml
void WriteFileToRequest (string filename, HttpWebRequest wr)
Writes the file in
filename
to the web request
wr
.
XmlDocument GetXmlResponse (HttpWebRequest wr)
Gets an XML document as the response from a web request.
Private Attributes
internal bool _resolveInbox = false
TODO: Whether the inbox URL should be resolved from the HTML of the supplied endpoint.
string _username
The repository username.
string _password
The repository password.
string _endpoint
The main repository endpoint.
Static Private Attributes
static int BUFFER_SIZE = 16 * 1024
Buffer size for uploads in bytes.
static string EP2_PACKAGING = "http://eprints.org/ep2/data/2.0"
EP2 packaging header value.
static string DOCX_CONTENTTYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
.docx content type
static string LIST_RECORD_PATH = "/id/records"
The path for listing records.
static string EXTRACT_MEDIA = "true"
Should media be extracted by default, or ignored? Note that this is going into a header so it should be a string rather than a Boolean.
Detailed Description
SWORD 2 client implementation for .NET.
Library functions for communicating with a SWORD 2 compliant server
Definition at line 35 of file SwordClientHandler.cs.
Constructor & Destructor Documentation
uk.ac.soton.ses.SwordClientHandler.SwordClientHandler (string username, string password, string endpoint)
Creates a new SWORD 2 handler instance.
Parameters:
username The repository username
password The repository password
endpoint The main repository endpoint
Definition at line 124 of file SwordClientHandler.cs.
        {
            this._username = username;
            this._password = password;
            this._endpoint = endpoint;
        }
uk.ac.soton.ses.SwordClientHandler.SwordClientHandler (string username, string password, string endpoint, bool resolveInbox)
Creates a new SWORD 2 handler instance.
Parameters:
username The repository username
password The repository password
endpoint The main repository endpoint
resolveInbox Whether to attempt to resolve the 'inbox' from the supplied endpoint
Definition at line 138 of file SwordClientHandler.cs.
        {
            this._username = username;
            this._password = password;
            this._endpoint = endpoint;
            this._resolveInbox = resolveInbox;
            this.ResolveInbox();
        }
Member Function Documentation
string uk.ac.soton.ses.SwordClientHandler.CreateContainer ()
Creates an empty container on the initialised repository.
Returns:
The address of the new empty container
Definition at line 381 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.SwordClientHandlerTests.TestCreateContainer().
        {
            return this.CreateContainer(this._endpoint);
        }
string uk.ac.soton.ses.SwordClientHandler.CreateContainer (string endpoint)
Creates an empty container on the repository at the supplied endpoint.
Parameters:
endpoint The endpoint at which to create the new empty container
Returns:
The address of the new empty container
Definition at line 391 of file SwordClientHandler.cs.
        {
            HttpWebRequest wr = this.GetBasicAuthAtomWebRequest(endpoint);
            wr.Method = "POST";
            wr.ContentType = "application/atom+xml";
            wr.Headers.Add("In-Progress", "true");
            string emptyAtom = @"<?xml version=""1.0"" encoding=""utf-8"" ?>
             <entry xmlns=""http://www.w3.org/2005/Atom"" />";
            wr.ContentLength = (long)emptyAtom.Length;
            // TODO: not the most elegant way to write this 'empty' Atom request
            // but functional
            using (Stream requestStream = wr.GetRequestStream())
            {
                foreach (byte b in emptyAtom)
                {
                    requestStream.WriteByte(b);
                }
            }
            return this.GetResponseLocation(wr);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.Delete (string swordUrl)
Deletes the document at the target address
swordUrl
.
Parameters:
swordUrl The target address at which the document resides
Returns:
Atom response
Definition at line 613 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.SwordClientHandlerTests.TestDelete().
        {
            HttpWebRequest wr = this.GetBasicAuthAtomWebRequest(swordUrl);
            wr.Method = "DELETE";
            return this.GetXmlResponse(wr);
        }
string uk.ac.soton.ses.SwordClientHandler.DepositDocxToContents (string docxFilename, string contentType, string contentUri)
Deposits the .docx from the supplied filename to the supplied endpoint with the supplied content type.
Parameters:
docxFilename The filename of the .docx to deposit
contentType The content type to use for the deposition
contentUri The endpoint against which the deposition should occur
Returns:
Atom response
Definition at line 299 of file SwordClientHandler.cs.
        {
            FileInfo fi = new FileInfo(docxFilename);
            HttpWebRequest wr = this.GetBasicAuthAtomWebRequest(contentUri);
            wr.Method = "POST";
            wr.Headers.Add("Content-Disposition", "form-data; name=\"" + fi.Name + "\"; filename=\"" + fi.Name + "\"");
            wr.ContentType = contentType;
            wr.ContentLength = fi.Length;
            // should the default be to extract media, or ignore it?
            wr.Headers.Add("X-Extract-Media", EXTRACT_MEDIA);
            wr.Headers.Add("X-Override-Metadata", "true");
            //wr.Headers.Add("Metadata-Relevant", "true");
            wr.Headers.Add("In-Progress", "true");
            this.WriteFileToRequest(docxFilename, wr);
            return this.GetResponseLocation(wr); //this.GetXmlResponse(wr);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.DepositEprintsXml (XmlDocument xmlDocument)
Deposits the EP2 XML document to the initialised endpoint with X-Packaging type
EP2_PACKAGING
Parameters:
xmlDocument The EP2 XML document to deposit
Returns:
Atom response
Definition at line 545 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.SwordClientHandlerTests.TestDepositEprintsXml().
        {
            return this.DepositXml(xmlDocument, EP2_PACKAGING);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.DepositEprintsXml (string xmlFileName)
Deposits the EP2 XML document in the supplied filename to the initialised endpoint with X-Packaging type
EP2_PACKAGING
Parameters:
xmlFileName The filename of the EP2 XML document to deposit
Returns:
Atom response
Definition at line 556 of file SwordClientHandler.cs.
        {
            return this.DepositXml(xmlFileName, EP2_PACKAGING);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.DepositXml (XmlDocument xmlDocument, string xPackaging)
Deposits the XML document to the initialised endpoint with the supplied X-Packaging type.
Parameters:
xmlDocument The XML document to deposit
xPackaging The X-Packaging type
Returns:
Atom response
Definition at line 582 of file SwordClientHandler.cs.
        {
            HttpWebRequest wr = this.GetBasicAuthAtomWebRequest(this._endpoint);
            wr.Method = "POST";
            wr.Headers.Add("X-Packaging", xPackaging);
            wr.ContentType = "text/xml";
            // note that we can't wrap the Stream here with a using as there
            // is a possibility that Dispose will get called more than once
            // and this will generate an ObjectDisposedException. Instead,
            // we'll not assign the request stream to anything and just
            // pass it through directly
            XmlWriterSettings xws = new XmlWriterSettings();
            xws.CloseOutput = true;
            using (XmlWriter xw = XmlWriter.Create(wr.GetRequestStream(), xws))
            {
                xmlDocument.WriteTo(xw);
                // ensure that the XML writer is flushes as this does *not* happen automatically
                xw.Flush();
            }
            return this.GetXmlResponse(wr);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.DepositXml (string xmlFileName, string xPackaging)
Deposits the XML document in the supplied filename to the initialised endpoint with the supplied X-Packaging type.
Parameters:
xmlFileName The filename of the XML document to deposit
xPackaging The X-Packaging type
Returns:
Atom response
Definition at line 568 of file SwordClientHandler.cs.
        {
            XmlDocument xmlDocument = new XmlDocument();
            xmlDocument.Load(xmlFileName);
            return this.DepositXml(xmlDocument, xPackaging);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.DepositZipToEprint (string zipFileName, string contentType)
Deposits the zip file in the supplied filename to the initalised endpoint with the supplied content type.
Parameters:
zipFileName The zip filename
contentType The content type
Returns:
Atom response
Definition at line 525 of file SwordClientHandler.cs.
        {
            FileInfo fi = new FileInfo(zipFileName);
            HttpWebRequest wr = this.GetBasicAuthAtomWebRequest(this._endpoint);
            wr.Method = "POST";
            wr.Headers.Add("Content-Disposition", "form-data; name=\"" + fi.Name + "\"; filename=\"" + fi.Name + "\"");
            wr.ContentType = contentType;
            wr.ContentLength = fi.Length;
            wr.Headers.Add("X-Extract-Archive", "true");
            this.WriteFileToRequest(zipFileName, wr);
            return this.GetXmlResponse(wr);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.DepositZipToEprint (string zipFileName)
Deposits the zip file in the supplied filename to the initialised endpoint with a gzip content type (to be formally standardised at the server side).
Parameters:
zipFileName The zip filename
Returns:
Atom response
Definition at line 513 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.SwordClientHandlerTests.TestDepositZipToEprint().
        {
            return this.DepositZipToEprint(zipFileName, "application/g-zip");
        }
HttpWebRequest uk.ac.soton.ses.SwordClientHandler.GetBasicAuthAtomWebRequest (string targetUri) [private]
Creates a web request instance to the target URI, adding in basic authorisation from the username and password on the instance, and setting the
accept
header of the request to be
application/atom+xml
Parameters:
targetUri The URI to which the request should be made
Returns:
Web request
Definition at line 173 of file SwordClientHandler.cs.
        {
            return this.GetBasicAuthAtomWebRequest(new Uri(targetUri));
        }
HttpWebRequest uk.ac.soton.ses.SwordClientHandler.GetBasicAuthAtomWebRequest (Uri targetUri) [private]
Creates a web request instance to the target URI, adding in basic authorisation from the username and password on the instance, and setting the
accept
header of the request to be
application/atom+xml
Parameters:
targetUri The URI to which the request should be made
Returns:
Web request
Definition at line 185 of file SwordClientHandler.cs.
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(targetUri);
            CredentialCache cc = new CredentialCache();
            cc.Add(targetUri, "Basic", new NetworkCredential(this._username, this._password, "Authenticate"));
            //cc.Add(new Uri(targetUri), "Basic", new NetworkCredential(this._username, this._password));
            request.Credentials = cc;
            request.Headers.Add(HttpRequestHeader.Authorization, "Basic " + Convert.ToBase64String(new ASCIIEncoding().GetBytes(this._username + ':' + this._password)));
            request.Accept = "application/atom+xml";
            return request;
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.GetEprintInfo (string uri)
Gets information about the ePrint at the provided URI.
Parameters:
uri ePrint URI
Returns:
Atom XML document
Definition at line 434 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.SwordClientHandlerTests.TestGetInfo().
        {
            HttpWebRequest wr = this.GetBasicAuthAtomWebRequest(uri);
            wr.Method = "GET";
            return this.GetXmlResponse(wr);
        }
string uk.ac.soton.ses.SwordClientHandler.GetResponseLocation (HttpWebRequest wr)
Gets the location of the response from the provided
HttpWebRequest
Parameters:
wr The web request to query
Returns:
Location string
Definition at line 419 of file SwordClientHandler.cs.
        {
            string location = null;
            using (HttpWebResponse resp = (HttpWebResponse)wr.GetResponse())
            {
                location = resp.Headers[HttpResponseHeader.Location].ToString();
            }
            return location;
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.GetXmlResponse (HttpWebRequest wr) [private]
Gets an XML document as the response from a web request.
The response will be
null
if it is invalid, either because it is not well-formed XML (e.g. HTML 4.0) or there was no acceptable response available from the server (e.g. 404)
Parameters:
wr The web request from which the response should be requested
Returns:
The XML document response
Definition at line 232 of file SwordClientHandler.cs.
        {
            XmlDocument xmlResponse = null;
            try
            {
                using (WebResponse res = wr.GetResponse())
                {
                    using (Stream resStream = res.GetResponseStream())
                    {
                        // when this method was implemented, the SWORD 2 server was still returning HTML:
                        // if (((HttpWebResponse)res).StatusCode == HttpStatusCode.OK)
                        // {
                        //    return null;
                        // }
                        // - so try/catch this in case it changes
                        try
{
                            xmlResponse = new XmlDocument();
                            xmlResponse.Load(resStream);
                        }
                        catch (XmlException xex)
{
                            Debug.WriteLine(xex);
                            // xmlResponse = null; // depends how we want to handle this
                        }
                    }
                }
            }
            catch (WebException wex)
            {
                // likely a 404, write the exception if we're in debug mode, and fall through
                // to return the null response
                Debug.WriteLine(wex);
            }
            return xmlResponse;
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.ListRecords ()
List all records at the endpoint, by calling endpoint/id/records (
LIST_RECORD_PATH
).
Returns:
List of records in XML format, else
null
Exceptions:
WebException Typically thrown at a timeout on the endpoint
Definition at line 695 of file SwordClientHandler.cs.
        {
            return this.ListRecords(false);
        }
XmlDocument uk.ac.soton.ses.SwordClientHandler.ListRecords (bool stripEndpoint)
List all records at the endpoint.
Parameters:
stripEndpoint
true
if the endpoint should be stripped down and the default of /id/records (
LIST_RECORD_PATH
) used, else
false
if the literal endpoint, suffixed with /id/records (
LIST_RECORD_PATH
) value should be used
Returns:
List of records in XML format, else
null
Exceptions:
WebException Typically thrown at a timeout on the endpoint
Definition at line 629 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.Word2010DepositMOAddIn.DepositMORepositoryControl.DumpListingToLog(), and uk.ac.soton.ses.SwordClientHandlerTests.TestList().
        {
            string target = this._endpoint;
            HttpWebRequest initialWr = null;
            HttpWebRequest realWr = null;
            WebResponse wresp = null;
            XmlDocument xmlDocument = null;
            if (stripEndpoint)
            {
                target = new Uri(this._endpoint).GetLeftPart(UriPartial.Authority);
            }
            string records = target + LIST_RECORD_PATH;
            Debug.WriteLine("Requesting records from " + records);
            initialWr = this.GetBasicAuthAtomWebRequest(records);
            initialWr.Method = "GET";
            try
            {
                wresp = initialWr.GetResponse();
            }
            catch (WebException wex)
            {
                // if we've timed out, rethrow the exception
                if (wex.Status == WebExceptionStatus.Timeout)
                {
                    throw wex;
                }
                // being forced to handle exceptions as part of normal program control
                // is not pleasant (303 in this case)
                Debug.WriteLine(wex.Response.ResponseUri);
                Uri realUri = wex.Response.ResponseUri;
                realWr = this.GetBasicAuthAtomWebRequest(realUri);
                realWr.Method = "GET";
                wresp = realWr.GetResponse();
            }
            using (Stream resStream = wresp.GetResponseStream())
            {
                try
                {
                    xmlDocument = new XmlDocument();
                    xmlDocument.Load(resStream);
                }
                catch (XmlException xex)
                {
                    Debug.WriteLine(xex);
                }
            }
            if (wresp != null)
            {
                wresp.Close();
            }
            return xmlDocument;
        }
string uk.ac.soton.ses.SwordClientHandler.PostDocxToContainer (string docxFilename, string contentType, string containerUri)
Posts the supplied docx file to the supplied container.
Parameters:
docxFilename The filename of the docx to post
contentType The content type of the docx
containerUri The URI of the container
Returns:
Definition at line 362 of file SwordClientHandler.cs.
References uk.ac.soton.ses.SwordAtomReader.EditMediaHref.
        {
            XmlDocument response = this.GetEprintInfo(containerUri);
            if (response == null) return null;
            SwordAtomReader sar = new SwordAtomReader(response);
            if (sar == null) return null;
            string editMediaHref = sar.EditMediaHref;
            Debug.WriteLine("Edit media href is {0}", editMediaHref);
            if (String.IsNullOrEmpty(editMediaHref)) return null;
            return this.DepositDocxToContents(docxFilename, contentType, editMediaHref);
        }
string uk.ac.soton.ses.SwordClientHandler.PostDocxToContainer (string docxFilename)
Deposits the .docx from the supplied filename to the initialised endpoint with the default content type.
Parameters:
docxFilename The filename of the .docx to deposit
Returns:
Atom response
Definition at line 276 of file SwordClientHandler.cs.
        {
            return this.PostDocxToContainer(docxFilename, DOCX_CONTENTTYPE);
        }
string uk.ac.soton.ses.SwordClientHandler.PostDocxToContainer (string docxFilename, string contentType)
Deposits the .docx from the supplied filename to the initialised endpoint with the supplied content type.
Parameters:
docxFilename The filename of the .docx to deposit
contentType The content type to use for the deposition
Returns:
Atom response
Definition at line 287 of file SwordClientHandler.cs.
        {
            return this.PostDocxToContainer(docxFilename, contentType, this._endpoint);
        }
string uk.ac.soton.ses.SwordClientHandler.PostDocxToRepository (string docxFilename, string contentType, string endpoint)
Creates a container on the repository and posts the supplied docx file to that container.
Parameters:
docxFilename The filename of the docx to post
contentType The content type of the docx
endpoint The endpoint against which the posting should occur
Returns:
Definition at line 326 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.Word2010DepositMOAddIn.DepositMORepositoryControl._SubmitDocument(), and uk.ac.soton.ses.SwordClientHandlerTests.TestPutToDocument().
        {
            string container = this.CreateContainer(endpoint);
            if (String.IsNullOrEmpty(container))
            {
                return null;
            }
            return this.PostDocxToContainer(docxFilename, contentType);
        }
string uk.ac.soton.ses.SwordClientHandler.PostDocxToRepository (string docxFilename)
Creates a container on the repository and posts the supplied docx file to that container, using the default docx content type and the initialised endpoint on the instance.
Parameters:
docxFilename The filename of the docx to post
Returns:
Definition at line 344 of file SwordClientHandler.cs.
        {
            string container = this.CreateContainer(this._endpoint);
            if (String.IsNullOrEmpty(container))
            {
                return null;
            }
            return this.PostDocxToContainer(docxFilename, DOCX_CONTENTTYPE, container);
        }
bool uk.ac.soton.ses.SwordClientHandler.PutToDocument (string documentFileName, string endpoint)
Performs a PUT to the supplied endpoint with the supplied document filename using
DOCX_CONTENTTYPE
.
This will update an existing entry on the SWORD target
Parameters:
documentFileName The filename of the document to use for the update
endpoint The endpoint against which the update should occur
Returns:
Atom response
Definition at line 448 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.Word2010DepositMOAddIn.DepositMORepositoryControl._SubmitDocument(), uk.ac.soton.ses.SwordClientHandlerTests.TestPutOnly(), and uk.ac.soton.ses.SwordClientHandlerTests.TestPutToDocument().
        {
            return this.PutToDocument(documentFileName, endpoint, DOCX_CONTENTTYPE);
        }
bool uk.ac.soton.ses.SwordClientHandler.PutToDocument (string documentFileName, string endpoint, string contentType)
Performs a PUT to the supplied endpoint with the supplied document filename using the supplied content type.
This will update an existing entry on the SWORD target
Parameters:
documentFileName The filename of the document to use for the update
endpoint The endpoint against which the update should occur
contentType The content type to use for the update
Returns:
Atom response
Definition at line 461 of file SwordClientHandler.cs.
        {
            HttpWebRequest wr = this.GetBasicAuthAtomWebRequest(endpoint);
            FileInfo fi = new FileInfo(documentFileName);
            wr.Method = "PUT";
            wr.Headers.Add("Content-Disposition", "form-data; name=\"" + fi.Name + "\"; filename=\"" + fi.Name + "\"");
            wr.ContentType = contentType;
            wr.ContentLength = fi.Length;
            wr.Headers.Add("X-Extract-Media", "true");
            wr.Headers.Add("X-Override-Metadata", "true");
            //wr.Headers.Add("Metadata-Relevant", "true");
            wr.Headers.Add("In-Progress", "true");
            this.WriteFileToRequest(documentFileName, wr);
            HttpWebResponse response = null;
            try
            {
                response = (HttpWebResponse)wr.GetResponse();
            }
            catch (WebException ex)
            {
                Debug.WriteLine(ex);
                if (ex.Response != null && ex.Response.Headers != null)
                {
                    foreach (HttpResponseHeader h in ex.Response.Headers)
                    {
                        Debug.WriteLine("Header: " + h.ToString());
                    }
                }
            }
            if (response == null) { return false; }
            bool responseOk = false;
            if (response.StatusCode == HttpStatusCode.OK)
            {
                responseOk = true;
            }
            if (response != null)
            {
                response.Close();
            }
            return responseOk;
        }
internal void uk.ac.soton.ses.SwordClientHandler.ResolveInbox () [private]
Resolves the inbox based on the currently-supplied endpoint.
Definition at line 150 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.SwordClientHandlerTests.TestResolveInbox().
        {
            // if we're not supposed to resolve the inbox, skip this step
            if (!this._resolveInbox)
            {
                return;
            }
            string inbox = HtmlScraper.GetAttributeContent(this._endpoint, "link", "rel", "SwordDeposit", "href");
            if (!String.IsNullOrEmpty(inbox))
            {
                this._endpoint = inbox;
            }
        }
void uk.ac.soton.ses.SwordClientHandler.WriteFileToRequest (string filename, HttpWebRequest wr) [private]
Writes the file in
filename
to the web request
wr
.
This uses a buffer whose size is stored statically in
BUFFER_SIZE
to speed up the transfer
Parameters:
filename The absolute filename to send
wr The web request on which to send the file
Definition at line 204 of file SwordClientHandler.cs.
        {
            wr.Timeout = 15000;
            using (Stream requestStream = wr.GetRequestStream())
            {
                using (FileStream fs = File.OpenRead(filename))
                {
                    int readCount;
                    byte[] buffer = new byte[BUFFER_SIZE];
                    while ((readCount = fs.Read(buffer, 0, buffer.Length)) != 0)
                    {
                        Debug.WriteLine(String.Format("Doing a block, at {0}", fs.Position));
                        requestStream.Write(buffer, 0, readCount);
                    }
                    Debug.WriteLine("Finished with input file");
                }
                Debug.WriteLine("Finished with output stream");
            }
        }
Member Data Documentation
string uk.ac.soton.ses.SwordClientHandler._endpoint [private]
The main repository endpoint.
Definition at line 83 of file SwordClientHandler.cs.
string uk.ac.soton.ses.SwordClientHandler._password [private]
The repository password.
Definition at line 78 of file SwordClientHandler.cs.
internal bool uk.ac.soton.ses.SwordClientHandler._resolveInbox = false [private]
TODO: Whether the inbox URL should be resolved from the HTML of the supplied endpoint.
TODO
Definition at line 68 of file SwordClientHandler.cs.
Referenced by uk.ac.soton.ses.SwordClientHandlerTests.TestResolveInbox().
string uk.ac.soton.ses.SwordClientHandler._username [private]
The repository username.
Definition at line 73 of file SwordClientHandler.cs.
int uk.ac.soton.ses.SwordClientHandler.BUFFER_SIZE = 16 * 1024 [static, private]
Buffer size for uploads in bytes.
Definition at line 40 of file SwordClientHandler.cs.
string uk.ac.soton.ses.SwordClientHandler.DOCX_CONTENTTYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document" [static, private]
.docx content type
Definition at line 50 of file SwordClientHandler.cs.
string uk.ac.soton.ses.SwordClientHandler.EP2_PACKAGING = "http://eprints.org/ep2/data/2.0" [static, private]
EP2 packaging header value.
Definition at line 45 of file SwordClientHandler.cs.
string uk.ac.soton.ses.SwordClientHandler.EXTRACT_MEDIA = "true" [static, private]
Should media be extracted by default, or ignored? Note that this is going into a header so it should be a string rather than a Boolean.
Definition at line 62 of file SwordClientHandler.cs.
string uk.ac.soton.ses.SwordClientHandler.LIST_RECORD_PATH = "/id/records" [static, private]
The path for listing records.
Definition at line 55 of file SwordClientHandler.cs.
Property Documentation
string uk.ac.soton.ses.SwordClientHandler.Endpoint [set]
Sets the endpoint associated with the repository.
Definition at line 111 of file SwordClientHandler.cs.
string uk.ac.soton.ses.SwordClientHandler.Password [set]
Sets the password associated with the repository.
Definition at line 100 of file SwordClientHandler.cs.
string uk.ac.soton.ses.SwordClientHandler.Username [set]
Sets the username associated with the repository.
Definition at line 89 of file SwordClientHandler.cs.
The documentation for this class was generated from the following file:
Q:/Projects/SwordHandler/SwordHandler/SwordClientHandler.cs